---
- name: Ansible Fact Demo
  hosts: nodes
  # gather_facts: false 
  tasks: 
    # - name: collect facts
      # setup:
    - name: Show Details
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_hostname }} {{ ansible_all_ipv4_addresses }} {{ ansible_env['SSH_CLIENT']}}"

# Play: ansible node1 -m setup
# ansible-playbook sites.yml