---
- name: Ejemplo de Copy
  hosts: node1

  tasks:
  - name: Copiar archivo
    copy:
      src: /tmp/archivo.tgz
      dest: /tmp/
  
  - name: Grabar en archivo
    copy:
      content: "Copiar contenido a fichero"
      dest: /tmp/fichero.txt

