---
- name: Trabajar con ficheros
  hosts: node1

  tasks:
  - name: Crear un fichero vacio
    file: 
      path: "/tmp/prueba.txt"
      state: "touch"
 
  - name: Borrar fichero anterior
    file:
      path: "/tmp/prueba.txt"
      state: "absent"
